### ISSUE TITLE
BYG fails to load on Forge Server 1.15.2

### ISSUE THREAD

**Issue by paulhlschr** [FoundSpore/BYG#17]
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 3/21/20 4:15 PM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Oh The Biomes You'll Go (byg) has failed to load correctly
ยง7Attempted to load class net/minecraft/client/renderer/color/BlockColors for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:altius_world/MixinMinecraftServer_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinMinecraftServer_MA,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.9.182-xxxx-std-ipv6-64
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 819661560 bytes (781 MB) / 2410676224 bytes (2299 MB) up to 4772593664 bytes (4551 MB)
	CPUs: 8
	JVM Flags: 1 total; -Xmx5G
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.27
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		torchslabmod-1.15.1_v1.5.jar Torch Slab Mod {torchslabmod@1.5.0 CREATE_REGISTRIES}
		AdvancedSkinCustomization-2.8.2.jar Advanced Skin Customization {advskinmod@2.8.2 CREATE_REGISTRIES}
		PersistentBits-1.15.2-2.0.1.jar Persistent Bits {persistentbits@2.0.1 CREATE_REGISTRIES}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 CREATE_REGISTRIES}
		buzzierbees-1.3.jar Buzzier Bees {buzzierbees@1.3 CREATE_REGISTRIES}
		AttributeFix-1.15.2-7.0.1.jar AttributeFix {attributefix@7.0.1 CREATE_REGISTRIES}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 CREATE_REGISTRIES}
		Mekanism-1.15.2-9.9.16.408.jar Mekanism {mekanism@9.9.16 CREATE_REGISTRIES}
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 CREATE_REGISTRIES}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 CREATE_REGISTRIES}
		rsgauges-1.15.2-1.2.2-b2.jar Gauges and Switches {rsgauges@1.2.2-b2 CREATE_REGISTRIES}
		TerraForged-1.15.2-0.0.7.jar TerraForged {terraforged@0.0.7 CREATE_REGISTRIES}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 CREATE_REGISTRIES}
		JRFTL [1.15.2]-1.1.jar JRFTL {jrftl@1.1 CREATE_REGISTRIES}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 CREATE_REGISTRIES}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 CREATE_REGISTRIES}
		SereneSeasons-1.15.2-3.0.0.68-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.68 CREATE_REGISTRIES}
		finitewater-1.0.jar Finite Water and Infinite Lava {finitewater@1.0 CREATE_REGISTRIES}
		premium-wood-1.15.2-1.1.0.jar Premium Wood {premium_wood@1.1.0 CREATE_REGISTRIES}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 CREATE_REGISTRIES}
		WoolToString-1.14.2-1.0.0.jar WoolToString {wooltostring@1.0.0 CREATE_REGISTRIES}
		Bookshelf-1.15.2-5.1.4.jar Bookshelf {bookshelf@5.1.4 CREATE_REGISTRIES}
		BotanyPots-1.15.2-2.0.4.jar BotanyPots {botanypots@2.0.4 CREATE_REGISTRIES}
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 CREATE_REGISTRIES}
		alib-1.15.2-1.jar A Lib {alib@1.15.2-1 CREATE_REGISTRIES}
		mcjtylib-1.15-4.0.2-alpha.jar McJtyLib {mcjtylib@1.15-4.0.2-alpha CREATE_REGISTRIES}
		rftoolsbase-1.15-1.0.0-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.0-alpha CREATE_REGISTRIES}
		xnet-1.15-2.0.1-alpha.jar XNet {xnet@1.15-2.0.1-alpha CREATE_REGISTRIES}
		ProgressiveBosses-2.1.4-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.4-mc1.15.2 CREATE_REGISTRIES}
		mapperbase-1.15.2-1.0.0.0.jar Mapper Base {mapperbase@1.15.2-1.0.0.0 CREATE_REGISTRIES}
		MekanismGenerators-1.15.2-9.9.16.408.jar Mekanism: Generators {mekanismgenerators@9.9.16 CREATE_REGISTRIES}
		dynviewdist-1.3.jar Dynamic view distance {dynview@1.2 CREATE_REGISTRIES}
		traverse-1.15.2-3.0.0.jar Traverse {traverse@1.15.2-3.0.0 CREATE_REGISTRIES}
		immersive-portals-0.8(forMc1.15withForge).jar Immersive Portals {immersive_portals@0.8 CREATE_REGISTRIES}
		rftoolspower-1.15-2.0.1-alpha.jar RFToolsPower {rftoolspower@1.15-2.0.1-alpha CREATE_REGISTRIES}
		campfiretorches-1.15.2-1.0.2.jar Campfire Torches {campfiretorches@1.15.2-1.0.2 CREATE_REGISTRIES}
		forge-1.15.2-31.1.27-universal.jar Forge {forge@31.1.27 CREATE_REGISTRIES}
		mysticallib-1.15.2-2.0.0.jar Mystical Lib {mysticallib@1.15.2-2.0.0 CREATE_REGISTRIES}
		corpse-1.15.2-1.0.2.jar Corpse {corpse@1.15.2-1.0.2 CREATE_REGISTRIES}
		replantingcrops_1.15-1.2.jar Replanting Crops {replantingcrops@1.2 CREATE_REGISTRIES}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 CREATE_REGISTRIES}
		alchemistry-1.15.2-5.jar Alchemistry {alchemistry@1.15.2-5 CREATE_REGISTRIES}
		forge-1.15.2-31.1.27-server.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 CREATE_REGISTRIES}
		industrial-foregoing-1.15.2-2.2.2-28d4a81.jar Industrial Foregoing {industrialforegoing@2.2.2 CREATE_REGISTRIES}
		theoneprobe-1.15-2.0.1.jar The One Probe {theoneprobe@1.15-2.0.1 CREATE_REGISTRIES}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 CREATE_REGISTRIES}
		embellishcraft-1.15.2-2.0.0.0.jar EmbellishCraft {embellishcraft@1.15.2-2.0.0.0 CREATE_REGISTRIES}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 CREATE_REGISTRIES}
		titanium-1.15.2-2.3.7.jar Titanium {titanium@2.3.7 CREATE_REGISTRIES}
		BiomesOPlenty-1.15.2-10.0.0.351-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.349 CREATE_REGISTRIES}
		phosphor-mc1.15.2-forge-0.4.2-rc2.jar Phosphor {phosphor@0.4.2-rc2 CREATE_REGISTRIES}
		rftoolsbuilder-1.15-2.0.0-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.0-alpha CREATE_REGISTRIES}
		goprone-1.15.x-1.1.1.jar GoProne {goprone@1.15.x-1.1.1 CREATE_REGISTRIES}
		Patchouli-1.15.2-1.2-28.jar Patchouli {patchouli@1.15.2-1.2-28 CREATE_REGISTRIES}
		JAOPCA-1.15.2-3.0.0.21.jar JAOPCA {jaopca@3.0.0.21 CREATE_REGISTRIES}
		rftoolsstorage-1.15-1.0.2-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.2-alpha CREATE_REGISTRIES}
		chemlib-1.15.2-2.jar Chem Lib {chemlib@1.15.2-2 CREATE_REGISTRIES}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 CREATE_REGISTRIES}
		extlights-2.0.jar Extended Lights {extlights@2.0 CREATE_REGISTRIES}
		horse_colors-1.15.2-1.1.3.jar Realistic Horse Genetics {horse_colors@1.15.2-1.1.2 CREATE_REGISTRIES}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 CREATE_REGISTRIES}
		DoubleSlabs-1.15-2.0.2.jar Double Slabs {doubleslabs@2.0.2 CREATE_REGISTRIES}
		backpacked-1.4.1-1.15.2.jar Backpacked {backpacked@1.4.1 CREATE_REGISTRIES}
		MekanismTools-1.15.2-9.9.16.408.jar Mekanism: Tools {mekanismtools@9.9.16 CREATE_REGISTRIES}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 CREATE_REGISTRIES}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 CREATE_REGISTRIES}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 CREATE_REGISTRIES}
		cc-tweaked-1.15.2-1.86.2.jar CC: Tweaked {computercraft@1.86.2 CREATE_REGISTRIES}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 CREATE_REGISTRIES}
		mcw-furnitures-1.0.0-mc1.15.2.jar Macaw's Furniture {mcwfurnitures@1.0.0 CREATE_REGISTRIES}
		solcarrot-1.15.2-1.9.4.jar Spice of Life: Carrot Edition {solcarrot@1.15.2-1.9.4 CREATE_REGISTRIES}
		water-erosion-1.15.2-forge-1.0.2.jar Water Erosion {water-erosion@1.0.2 CREATE_REGISTRIES}
		Biomes_You_Go_0.1.0.jar Oh The Biomes You'll Go {byg@0.0.1 ERROR}
		Aquaculture-1.15.2-2.0.11.jar Aquaculture 2 {aquaculture@1.15.2-2.0.11 CREATE_REGISTRIES}
		tramplestopper-1.15.2-2.0.0.1-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.1-universal CREATE_REGISTRIES}
		waterworks-1.15.2-2.1.1.jar Waterworks {waterworks@1.15.2-2.1.1 CREATE_REGISTRIES}
		BetterBurning-1.15.2-1.3.1.jar BetterBurning {betterburning@1.3.1 CREATE_REGISTRIES}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 CREATE_REGISTRIES}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by FoundSpore** [comment]
This has been patched in the latest version! Thank You for the report!

https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/2908167
